### Today, I am going to perform a merge between two DataFrames.

#### In this case, I will be working with two DataFrames containing e-commerce data.

In [1]:
import pandas as pd

# Dataframe 1: Daily sales transactions

sales_data = {
    'Transaction_ID': [1001, 1002, 1003, 1004, 1005],
    'Product_ID': [10, 30, 20, 10, 40],
    'Quantity_Sold': [2, 1, 3, 1, 2]
}
df_sales = pd.DataFrame(sales_data)

# Dataframe 2: Product Catalog

product_data = {
    'Product_ID': [10, 20, 30, 40],
    'Product_Name': ['Mechanical Keyboard', 'Gaming Mouse', 'Monitor 24"', 'Headset'],
    'Unit_Price': [50.0, 30.0, 150.0, 80.0]
}
df_products = pd.DataFrame(product_data)

print("Sales Table:")
display(df_sales)

print("\nProducts Table:")
display(df_products)

Sales Table:

   Transaction_ID  Product_ID  Quantity_Sold
0            1001          10              2
1            1002          30              1
2            1003          20              3
3            1004          10              1
4            1005          40              2

Products Table:

   Product_ID         Product_Name  Unit_Price
0          10  Mechanical Keyboard        50.0
1          20         Gaming Mouse        30.0
2          30          Monitor 24"       150.0
3          40              Headset        80.0

#### As we can see in the sales DataFrame, we only have the ID of the product sold, but we lack additional information like the price, name, etc.
#### So, the first logical step is to create a new DataFrame by merging the two existing ones.

In [3]:
df_merged = pd.merge(df_sales, df_products, on='Product_ID', how= 'inner')

#### The second step is to extract value from this merged data. In this case, I am going to create a new column to reflect the total revenue generated in every sale.
#### For this, I am creating a new variable called 'Total_revenue', which is the result of multiplying the 'Quantity_Sold' and 'Unit_Price' columns.

In [4]:
df_merged['Total_revenue'] = df_merged['Quantity_Sold'] * df_merged['Unit_Price']

# And now we show the final dataframe

print("Final Dataframe: ")
display(df_merged)

Final Dataframe:

,Transaction_ID,Product_ID,Quantity_Sold,Product_Name,Unit_Price,Total_revenue
0,1001,10,2,Mechanical Keyboard,50.0,100.0
1,1002,30,1,"Monitor 24""",150.0,150.0
2,1003,20,3,Gaming Mouse,30.0,90.0
3,1004,10,1,Mechanical Keyboard,50.0,50.0
4,1005,40,2,Headset,80.0,160.0